### ISSUE TITLE
Half Membrane Output in Mean Coordinate Calculation

### ISSUE THREAD

**Issue by aashuph16221** [MOSAICS-NIH/MOSAICS#4]
Hello,

I am conducting a simulation of a POPC membrane (all-atom simulation) and attempting to calculate the mean average coordinate. However, I am encountering an issue where the calculation only provides half of the membrane. I'm a bit confused about why this is happening within the system. 

Could you please provide guidance on this problem?

Regards,

Aashish

![Screenshot from 2023-12-13 10-45-31](https://github.com/MOSAICS-NIH/MOSAICS/assets/135867974/15329285-dd89-47ba-b9ad-0318be8e1719)

**Comment by bernhardtna** [comment]
Hi Aashish. I would be happy to help you with this. Can you please clarify when you refer to "half of the membrane", do you mean you get only one leaflet for the output. Or, do you mean something else, like you only get the left half of the membrane, etc. From the picture you have provided ,it looks like you are using the Mean Lipid Coords program which generates data for a single leaflet at a time. You can specify which, upper or lower, using the -leaf command line argument (1: upper, 2:lower). Then, to get the full membrane, you just run the analysis for each leaflet separately and load the resulting data files into PyMOL or VMD etc. 

Hope this helps, 
Nathan

**Comment by aashuph16221** [comment]
Hi,

I apologize for the delayed message.

I'm attempting to calculate the average mean coordinate. When utilizing the DLPC system, it creates results consistent with the manual's description. However, with the POPC system, it consistently becomes disorganized.

I have included the entire membrane (red)  in the (xy axis) with an average upper leaflet (blue). My POPC lipid measures approximately 160 Å. Despite my efforts to align the entire trajectory, the issue persists.

Could you please provide guidance on how to proceed?

Regards,

Aashish

![POPC_mem](https://github.com/MOSAICS-NIH/MOSAICS/assets/135867974/d1b81417-fe32-4836-a1b1-f943a6bdb5c6)

**Comment by bernhardtna** [comment]
From the image you have provided, it looks like your trajectory is centered at the origin, i.e., (0,0,0). This is common practice for trajectories generated with programs like NAMD, although I am not certain if that is the program you used to generate the trajectory. Contrast to this, programs like GROMACS place the molecular system inside a box whose bottom left corner sits at the origin. MOSAICS then follows the GROMACS convention such that all of the grid-based analysis (like the mean lipid coords) generates a grid whose bottom left corner sits at the origin (see the attached pic). In this case, you would need to translate your box so that it overlaps with the MOSAICS grid. As it stands, all the lipids that are outside of the grid are left out of the analysis. If you have access to GROMACS, then you could fix the problem with trjconv using the -trans 8 8 0.5bz  option to shift the trajectory by half the box size and -pbc res to make sure everything stays in the box. Note, the 8 8 0.5*bz suggestions come from half the box size (16nm) and half the size of the z-component (bz) which I don't know. You can always figure out how much to shift by if you get the box dimensions for one of the trajectory frames, or ideally from your reference file (-ref). Then shift in each direction by half those dimensions.   
 
![box](https://github.com/MOSAICS-NIH/MOSAICS/assets/68967438/1e0eb133-3405-422e-91f6-c5ca0cec7b96)

**Comment by aashuph16221** [comment]
Thank you very much for you help.

I have aligned my trajectory, and now it shows perfectly fine results.
Thank you for the help, and I'm sorry to bother you.

Regards,
Aashish
