### ISSUE TITLE
std::logic_error

### ISSUE THREAD

**Issue by hsmartinho** [MOSAICS-NIH/MOSAICS#7]
Hello everyone,
I am installed MOSAICS on Debian 12 and after trying to run cited examples I always observe as output the message:
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid
Any clues concerning this issue?
Many thanks,
Herculano

**Comment by bernhardtna** [comment]
Hi Herculano, 
Thank you for reporting this issue. MOSAICS has been tested on the Biowulf computing cluster which uses Linux (Rocky 8). Unfortunately, I am unable to debug the error reported here without access to a machine running Debian 12 since I am unable to reproduce the error on Biowulf. I would be happy to investigate. However, I would need access to a cluster running Debian, perhaps a guest account is possible? Alternatively, you could try installing on a cluster supporting Linux if you have access to one. 
Hope this helps.
Nathan

**Comment by hsmartinho** [comment]
Thank you for your response. I find the problem. It was related to my input
files.
Best regards,
Herculano

Em sex., 8 de nov. de 2024, 16:53, bernhardtna ***@***.***>
escreveu:
